---
container_name: infra_landing_page
container_image: regi.sevensteves.com/infra-landing-page:latest
deploy_dir: /opt/infra_landing_page
landing_domain: landing.sevensteves.com
target_host: sjl-dwork-01.home
